### PR TITLE
[BREAKING] Default to `CurrentCulture`, add `culture` parameter to `FormatMessage`, upgrade to .NET 10

### LINKED ISSUE #41: Support InvariantGlobalization / default to InvariantCulture
When enabling [InvariantGlobalization](https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md) (which I believe is now the default in API/gRPC/Worker project templates), the library fails with:

```
System.Globalization.CultureNotFoundException : Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')

en is an invalid culture identifier.

   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at Jeffijoe.MessageFormat.Formatting.Formatters.VariableFormatter.GetCultureInfo(String locale)
   at Jeffijoe.MessageFormat.Formatting.Formatters.VariableFormatter.Format(String locale, FormatterRequest request, IReadOnlyDictionary`2 args, Object value, IMessageFormatter messageFormatter)
   at Jeffijoe.MessageFormat.MessageFormatter.FormatMessage(String pattern, IReadOnlyDictionary`2 args)
```

Would it make sense to default to the invariant culture (empty string `""`) instead of `"en"`?

This affects static usage – with a custom instance you could simply specify the locale/culture yourself.

It's a breaking change, but worth it in my opinion.

An alternative would be to allow the locale on the default instance to be set.

### PR DESCRIPTION
**Pull request by jeffijoe**
This PR changes the default culture to `CurrentCulture`, adds a `CultureInfo? culture = null`  parameter to `FormatMessage`, and upgrades the build targeting to `net10`, dropping `net6`. Also migrated from Source Generator to Incremental Generator API for the plural rules generator, as well as updated packages.

**These are all breaking changes.**

Closes #41

### CODE REVIEW

**Comment by jeffijoe** [comment]
@glen-84 @NightOwl888 It took a few years but we did it! Please take a look, let me know if there's anything we should change.

@sfuqua, as a recent contributor who did some fantastic work and has familiarized yourself with the code, I would love it if you would take a look as well.

File: src/Jeffijoe.MessageFormat/Formatting/Formatters/PluralFormatter.cs [hunk 1]
```diff
@@ -148,6 +149,7 @@ public string Format(string locale,
             throw new MessageFormatterException($"Unsupported plural formatter name: {request.FormatterName}");
         }
 
+        var locale = culture.Name;
```
Comment (sfuqua) [inline src/Jeffijoe.MessageFormat/Formatting/Formatters/PluralFormatter.cs:152]: I'm suspecting it'd be beneficial to keep an overload that takes `string locale` and have the new `CultureInfo` overload pass `culture.Name` in, so that callers can either work in a model where they're mapping to `CultureInfo` internally at all times and leveraging that with the lib, or working with more flexible locale identifiers for their scenario that can match against the CLDR data.

There are some cases I think where the CLDR rules for canonicalization are subtly different from how .NET normalizes via `CultureInfo` - and `CultureInfo` validation also depends on the runtime environment and I believe (would need to double check) the ICU rules associated with the runtime

there are also specific Unicode locale identifiers that won't map successfully to CultureInfos, and it'd be a same to have no entry point for that kind of data

**Review by sfuqua — APPROVED** [review]
lgtm overall! I'm on the fence about the CultureInfo vs string comment I left - I see some real value in exposing a way to call `FormatMessage()` with either ` string or a parsed Culture and it'd provide an escape hatch for inconsistencies between the Framework the CLDR data shipped with the package, if you can stomach having IFormatter needing to support it as well.

File: src/Jeffijoe.MessageFormat/Formatting/Formatters/PluralFormatter.cs (hunk 1 above)
Comment (jeffijoe) [reply src/Jeffijoe.MessageFormat/Formatting/Formatters/PluralFormatter.cs:152]: That's an interesting one. But if CultureInfo doesn't support those, then using those specifiers would break the value formatting, right? Or what would happen there?

Comment (sfuqua) [reply src/Jeffijoe.MessageFormat/Formatting/Formatters/PluralFormatter.cs:152]: Aha, I was tunnel visioned on CLDR and plurals 😁

I just tested several examples (against .NET 10) of cultures where the Unicode canonicalization _might_ cause problems with plurals and all of them had legacy languages in the plural CLDR data, so this is probably not worth worrying about right now.

I was trying to get it to throw on interesting examples but unless I passed `true` to GetCultureInfo, I didn't encounter any problems even if it didn't understand the subtags.

If the lib ever consumes additional CLDR data where inheritance and fallbacks start to cause divergences, it may be worth revisiting - and would want to start looking into proper Unicode canonicalization and aliasing at that point, but for the plural dataset it seems unnecessary.

Comment (jeffijoe) [reply src/Jeffijoe.MessageFormat/Formatting/Formatters/PluralFormatter.cs:152]: Yeah, if it got to that point, I'd say we should introduce our own data structure for the locale info. So basically you don't think this will be a problem? Good to merge?

Comment (sfuqua) [reply src/Jeffijoe.MessageFormat/Formatting/Formatters/PluralFormatter.cs:152]: Yup agreed! Seems reasonable and any issues cropping up in the wild can be fixed later as needed without major risk.
